---
- name: Deploying the build environment
  hosts: ubuntu
  become: yes
  tasks:
    - name: Update cache
      apt:
        update_cache: yes
    - name: Install needed packages
      apt:
        pkg:
          - docker
          - docker-compose
          - prometheus-node-exporter
    - name: Start docker-compose
      community.docker.docker_compose:
        project_src: docker
